http:
  port: 8080
admin:
  port: 9876
  host: localhost

# Service Endpoint
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'

  # Cars Service
  carsService:
    url: 'http://localhost:3005/'

  # Trucks Service
  trucksService:
    url: 'http://localhost:3006/'
  #
  combinedService:
    url: 'http://localhost:3007/'


# API Endpoint
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
# Cars Service
  createCars:
    paths: '/carsService/createCars'
  readCars:
    paths: '/carsService/readCars'
  updateCars:
    paths: '/carsService/updateCars/:id'
  deleteCars:
    paths: '/carsService/deleteCars/:id'

# Trucks Service
  createTrucks:
    paths: '/trucksService/createTrucks'
  readTrucks:
    paths: '/trucksService/readTrucks'
  updateTrucks:
    paths: '/trucksService/updateTrucks/:id'
  deleteTrucks:
    paths: '/trucksService/deleteTrucks/:id'

  readService:
    paths: '/combined/Read'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  
  
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  # Cars Service
  createCars:
    apiEndpoints:
      - createCars
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'POST'
      - proxy:
          action:
            serviceEndpoint: carsService 
            changeOrigin: true

  readCars:
    apiEndpoints:
      - readCars
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          action:
            serviceEndpoint: carsService 
            changeOrigin: true

  updateCars:
    apiEndpoints:
      - updateCars 
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'UPDATE'
      - proxy:
          action:
            serviceEndpoint: carsService 
            changeOrigin: true
  deleteCars:
    apiEndpoints:
      - deleteCars
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'DELETE'
      - proxy:
          action:
            serviceEndpoint: carsService 
            changeOrigin: true
 

# TrucksService
  createTrucks:
    apiEndpoints:
      - createTrucks
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'POST'
      - proxy:
          action:
            serviceEndpoint: trucksService 
            changeOrigin: true

  readTrucks:
    apiEndpoints:
      - readTrucks
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          action:
            serviceEndpoint: trucksService 
            changeOrigin: true

  updateTrucks:
    apiEndpoints:
      - updateTrucks 
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'PATCH'
      - proxy:
          action:
            serviceEndpoint: trucksService 
            changeOrigin: true

  deleteTrucks:
    apiEndpoints:
      - deleteTrucks
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'DELETE'
      - proxy:
          action:
            serviceEndpoint: trucksService 
            changeOrigin: true

  readService:
      apiEndpoints:
        - readService
      policies:
        - cors:
            - action:
                origin: '*'
                methods: 'GET'
        - proxy:
            - action:
                serviceEndpoint: combinedService
                changeOrigin: true


